### ISSUE TITLE
Options: Delta is always nil

### ISSUE THREAD

**Issue by arielfaur** [MarketDataApp/sdk-go#2]
HI!
I may be doing something wrong while trying to fetch historical option data for SPX.  Is there anything I need to set in order to get the greeks?

`resp, err := api.OptionChain().UnderlyingSymbol("SPX").Side("call").Date("2024-07-24").DTE(60).StrikeLimit(10).Get()`

`OptionQuote{OptionSymbol: "SPXW240920C05435000", Underlying: "SPX", Expiration: 2024-09-20 16:00:00 -04:00, Side: "call", Strike: 5435, FirstTraded: 2024-06-24 09:30:00 -04:00, DTE: 58, Ask: 151.2, AskSize: 7, Bid: 150.6, BidSize: 7, Mid: 150.9, Last: 229.77, Volume: 0, OpenInterest: 46, UnderlyingPrice: 5427.1299, InTheMoney: false, Updated: "2024-07-24 16:00:00 -04:00", IV: nil, Delta: nil, Gamma: nil, Theta: nil, Vega: nil, Rho: nil, IntrinsicValue: 0, ExtrinsicValue: 150.9}`

**Comment by MarketDataApp** [comment]
Our API does not currently provide greeks or IV for historical data.
